---
- name: Install node and npm
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: Symlink node to nodejs
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

- name: Install yarn
  npm:
    name: yarn
    global: yes
    state: present
